/* QUESTAO 7*/
select VALOR_IPVA, PLACA, MODELO, ANO_FABRICACAO from VEICULO
where (MODELO LIKE '%FORD%') AND (ANO_FABRICACAO LIKE '1997' 
OR ANO_FABRICACAO LIKE '1988' 
OR ANO_FABRICACAO LIKE '1996' 
OR  ANO_FABRICACAO LIKE '1990')
AND VALOR_IPVA BETWEEN 200 AND 800