/* QUESTAO 9*/
select COD_PROPRIETARIO, NOME, CIDADE, ESTADO from PROPRIETARIO

insert into PROPRIETARIO (COD_PROPRIETARIO, NOME, CIDADE, ESTADO) VALUES ('4926', 'ANA LUIZA', 'BETIM', 'MG');
insert into PROPRIETARIO (COD_PROPRIETARIO, NOME, CIDADE, ESTADO) VALUES ('3323', 'JULIA', 'BELO HORIZONTE', 'MG');
insert into PROPRIETARIO (COD_PROPRIETARIO, NOME, CIDADE, ESTADO) VALUES ('4298', 'GUSTAVO', 'SABARA', 'MG');
insert into PROPRIETARIO (COD_PROPRIETARIO, NOME, CIDADE, ESTADO) VALUES ('5841', 'MATHEUS', 'TEÓFILO OTONI', 'MG');
insert into PROPRIETARIO (COD_PROPRIETARIO, NOME, CIDADE, ESTADO) VALUES ('8847', 'RICARDO', 'IRECÊ', 'BA');

select * from VEICULO
insert into VEICULO (PLACA, MODELO, ANO_FABRICACAO, VALOR_IPVA, COD_PROPRIETARIO) VALUES ('ALS9988', 'FORD MUSTANG', '1998', NULL, '4926');
insert into VEICULO (PLACA, MODELO, ANO_FABRICACAO, VALOR_IPVA, COD_PROPRIETARIO) VALUES ('JCM9988', 'BUGATTI LA VOITURE NOIRE', '2021', NULL, '3323');
insert into VEICULO (PLACA, MODELO, ANO_FABRICACAO, VALOR_IPVA, COD_PROPRIETARIO) VALUES ('GLM9988', 'BMW', '2020', NULL, '4298');
insert into VEICULO (PLACA, MODELO, ANO_FABRICACAO, VALOR_IPVA, COD_PROPRIETARIO) VALUES ('MTH9988', 'HONDA CITY', '1945', NULL, '5841');
insert into VEICULO (PLACA, MODELO, ANO_FABRICACAO, VALOR_IPVA, COD_PROPRIETARIO) VALUES ('RCD9988', 'KOMBI', '1957', NULL, '8847');
