/* QUESTAO 2*/
select NOME, ESTADO from PROPRIETARIO
where ESTADO = 'MG' OR (ESTADO = 'RJ')
OR (ESTADO = 'CE')
OR (ESTADO = 'SP')
OR (ESTADO = 'PR')
ORDER BY NOME

select NOME, ESTADO from PROPRIETARIO
where ESTADO = 'MG' OR (ESTADO = 'RJ')
OR (ESTADO = 'CE')
OR (ESTADO = 'SP')
OR (ESTADO = 'PR')
ORDER BY ESTADO
