
Select PLACA, MODELO, VALOR_IPVA FROM VEICULO A 
Where COD_PROPRIETARIO IN (select COD_PROPRIETARIO FROM PROPRIETARIO where ESTADO  IN  ('MG'))
GROUP BY PLACA, MODELO,VALOR_IPVA HAVING VALOR_IPVA > (Select avg(VALOR_IPVA) FROM VEICULO A JOIN PROPRIETARIO B ON A.COD_PROPRIETARIO = B.COD_PROPRIETARIO WHERE ESTADO = 'SP')