SELECT MODELO , PLACA, CIDADE FROM VEICULO A JOIN PROPRIETARIO B
ON A.COD_PROPRIETARIO = B.COD_PROPRIETARIO
where VALOR_IPVA < (SELECT AVG(VALOR_IPVA) FROM VEICULO A JOIN PROPRIETARIO B ON A.COD_PROPRIETARIO = B.COD_PROPRIETARIO where B.CIDADE = B.CIDADE)