select ESTADO, PLACA, MODELO, VALOR_IPVA, NOME from PROPRIETARIO A join VEICULO B
ON A.COD_PROPRIETARIO = B.COD_PROPRIETARIO
Where ESTADO IN ('MG', 'RJ') AND VALOR_IPVA BETWEEN 150 AND 350  
ORDER BY ESTADO, PLACA