SELECT MODELO, CIDADE, AVG(VALOR_IPVA) AS Media from PROPRIETARIO A full outer join VEICULO B 
ON A.COD_PROPRIETARIO = B.COD_PROPRIETARIO 
where CIDADE = 'Belo Horizonte' AND MODELO <> 'FIAT' AND MODELO <> 'FIAT ELBA'
GROUP BY CIDADE, MODELO ORDER BY AVG(VALOR_IPVA